<?php

function echoRoles($roles)
{
    echo '<ul>';
    foreach ($roles as $role) {
        echo '<li>', $role->getName(), '</li>';
        if (!$role->hasChildren()) {
            continue;
        }
        echoRoles($role->getChildren());
    }
    echo '</ul>';
}

;

?>
    <h1 class="page-header">
        Your dashboard
    </h1>
    <p>
        You currently have access to the following roles:
    </p>
<?php echo echoRoles($this->identity()->getRoles()) ?>