<?php
/**
 * @copyright 2018 Internalsystemerror Limited
 */
declare(strict_types=1);

use Ise\Admin\Entity\Role;

/**
 * Display the roles
 *
 * @param iterable $roles
 *
 * @return void
 */
function echoRoles(iterable $roles): void
{
    echo '<ul>';
    foreach ($roles as $role) {
        if (!$role instanceof Role) {
            continue;
        }

        echo '<li>', $role->getName(), '</li>';
        if (!$role->hasChildren()) {
            continue;
        }
        echoRoles($role->getChildren());
    }
    echo '</ul>';
}

?>
    <h1 class="page-header">
        Your dashboard
    </h1>
    <p>
        You currently have access to the following roles:
    </p>
<?php echoRoles($this->identity()->getRoles()) ?>