<?php
/**
 * @copyright 2018 Internalsystemerror Limited
 */
declare(strict_types=1);

use Zend\Form\Fieldset;
use Zend\Form\Form;

/**
 * @var Form     $form
 * @var Fieldset $buttons
 */

// Prepare form
$form->setAttribute('action', $this->url(null, [], null, true));
$form->setAttribute('class', 'form-horizontal');

?>
    <h1 class="page-header">
        Edit Profile
    </h1>
<?php
// Prepare form
$buttons = $form->get('buttons');
$cancel  = $buttons->get('cancel');
$cancel->setAttribute('href', $this->url('zfcuser/profile'));
$form->prepare();

// Create form
echo $this->form()->openTag($form);
foreach ($form as $element) {
    switch (true) {
        case $element instanceof \Zend\Form\FieldsetInterface:
            echo $this->formCollection($element);
            break;
        case $element instanceof \Zend\Form\Element\Email:
            $elementString = '<p class="form-control-static">'
                             . $element->getValue() . ' <a href="'
                             . $this->url('zfcuser/changeemail') . '">(Update)</a></p>';
            echo $this->formRow()->renderGroup($element, $elementString);
            break;
        case $element instanceof \Zend\Form\Element\Password:
            $elementString = '<p class="form-control-static"><a href="'
                             . $this->url('zfcuser/changepassword')
                             . '">Change Password</a></p>';
            echo $this->formRow()->renderGroup($element, $elementString);
            break;
        default:
            echo $this->formRow($element);
            break;
    }
}

echo $this->form()->closeTag();
