<?php
/**
 * @copyright 2018 Internalsystemerror Limited
 */
declare(strict_types=1);

use Ise\Admin\Entity\User;
use Zend\View\Helper\Gravatar;

/**
 * @var Gravatar $gravatar
 * @var User     $user
 */

// Set up gravatar
$gravatar = $this->gravatar();
$gravatar->setEmail($user->getEmail());
$gravatar->setImgSize(300);
$gravatar->setDefaultImg(Zend\View\Helper\Gravatar::DEFAULT_IDENTICON);
$gravatar->setAttributes(['class' => 'img-responsive img-thumbnail center-block']);

?>
<h1 class="page-header">
    User Profile
</h1>
<form class="form-horizontal">
    <div class="row">
        <div class="col-sm-4 col-md-3 col-lg-2">
            <div class="form-group">
                <div class="col-sm-12">
                    <?php echo $gravatar ?>
                </div>
            </div>
        </div>
        <div class="col-sm-8 col-md-9 col-lg-10">
            <div class="form-group">
                <div class="col-sm-12">
                    <h4 class="page-header">
                        Login Details
                    </h4>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2 control-label">Username</label>
                <div class="col-sm-10">
                    <p class="form-control-static">
                        <?php echo $this->escapeHtml($user->getUsername()) ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-12">
            <h4 class="page-header">
                Profile Details
            </h4>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Display Name</label>
        <div class="col-sm-10">
            <p class="form-control-static">
                <?php echo $this->escapeHtml($user->getDisplayName()) ?>
            </p>
        </div>
    </div>
</form>