<?php
/**
 * @copyright 2018 Internalsystemerror Limited
 */
declare(strict_types=1);

use Ise\Bread\EventManager\BreadEvent;

?>
<h1 class="page-header">
    Browsing <?php echo $entityTitle, substr($entityTitle, -1, 1) !== 's' ? 's' : null ?>
    <?php if ($this->isGranted($basePermission . '.' . BreadEvent::ACTION_CREATE)): ?>
        <a class="btn btn-primary pull-right" role="button" title="Create new <?php echo $entityTitle ?>"
           href="<?php echo $this->url($indexRoute . '/' . BreadEvent::ACTION_CREATE) ?>">
            <span class="glyphicon glyphicon-plus"></span>
        </a>
    <?php endif ?>
</h1>
<table class="data-table table table-striped table-bordered table-hover">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Last Modified</th>
        <th>Created</th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    <?php
    if ($this->isGranted($basePermission)):
        foreach ($list as $entity):
            if (!$this->isGranted($basePermission, $entity)) {
                continue;
            }
            ?>
            <tr<?php echo $entity->isDisabled() ? ' class="danger"' : null ?>>
                <td><?php echo $this->escapeHtml($entity->getId()) ?></td>
                <td><?php echo $this->escapeHtml($entity->getName()) ?></td>
                <td><?php echo $this->escapeHtml($entity->getDescription()) ?></td>
                <td><?php echo $this->time($entity->getLastModified()) ?></td>
                <td><?php echo $this->time($entity->getCreated()) ?></td>
                <td>
                    <?php if ($entity->isDisabled()): ?>
                        <?php if ($this->isGranted($basePermission . '.' . BreadEvent::ACTION_ENABLE, $entity)): ?>
                            <a class="btn btn-success" role="button" title="Enable <?php echo $entityTitle ?>"
                               href="<?php echo $this->url($indexRoute . '/' . BreadEvent::ACTION_ENABLE,
                                   [BreadEvent::IDENTIFIER => $entity->getId()]) ?>">
                                <span class="glyphicon glyphicon-off"></span>
                            </a>
                        <?php endif ?>
                    <?php else: ?>
                        <div class="btn-group" role="group" aria-label="Actions">
                            <a class="btn btn-primary" role="button" title="View <?php echo $entityTitle ?>"
                               href="<?php echo $this->url($indexRoute . '/' . BreadEvent::ACTION_READ,
                                   [BreadEvent::IDENTIFIER => $entity->getId()]) ?>">
                                <span class="glyphicon glyphicon-eye-open"></span>
                            </a>
                            <?php if ($this->isGranted($basePermission . '.' . BreadEvent::ACTION_UPDATE, $entity)): ?>
                                <a class="btn btn-info" role="button" title="Edit <?php echo $entityTitle ?>"
                                   href="<?php echo $this->url($indexRoute . '/' . BreadEvent::ACTION_UPDATE,
                                       [BreadEvent::IDENTIFIER => $entity->getId()]) ?>">
                                    <span class="glyphicon glyphicon-pencil"></span>
                                </a>
                            <?php endif ?>
                            <?php if ($this->isGranted($basePermission . '.' . BreadEvent::ACTION_DELETE, $entity)): ?>
                                <a class="btn btn-danger" role="button" title="Delete <?php echo $entityTitle ?>"
                                   href="<?php echo $this->url($indexRoute . '/' . BreadEvent::ACTION_DELETE,
                                       [BreadEvent::IDENTIFIER => $entity->getId()]) ?>">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </a>
                            <?php endif ?>
                            <?php if ($this->isGranted($basePermission . '.' . BreadEvent::ACTION_DISABLE, $entity)): ?>
                                <a class="btn btn-warning" role="button" title="Disable <?php echo $entityTitle ?>"
                                   href="<?php echo $this->url($indexRoute . '/' . BreadEvent::ACTION_DISABLE,
                                       [BreadEvent::IDENTIFIER => $entity->getId()]) ?>">
                                    <span class="glyphicon glyphicon-off"></span>
                                </a>
                            <?php endif ?>
                        </div>
                    <?php endif ?>
                </td>
            </tr>
        <?php
        endforeach;
    endif;
    ?>
    </tbody>
</table>