<?php
// Prepare form
$form->setAttribute('action', $this->url(null, array(), null, true));
$form->setAttribute('class', 'form-horizontal');

?>
<h1 class="page-header">
    Edit Profile
</h1>
<?php
// Prepare form
$cancel = $form->get('buttons')->get('cancel');
$cancel->setAttribute('href', $this->url('zfcuser/profile'));
$form->prepare();

// Create form
echo $this->form()->openTag($form);
foreach ($form as $element) {
    switch (true) {
        case $element instanceof \Zend\Form\FieldsetInterface:
            echo $this->formCollection($element);
            break;
        case $element instanceof \Zend\Form\Element\Email:
            $elementString = '<p class="form-control-static">'
                . $element->getValue() . ' <a href="'
                . $this->url('zfcuser/changeemail') . '">(Update)</a></p>';
            echo $this->formRow()->renderGroup($element, $elementString);
            break;
        case $element instanceof \Zend\Form\Element\Password:
            $elementString = '<p class="form-control-static"><a href="'
                . $this->url('zfcuser/changepassword')
                . '">Change Password</a></p>';
            echo $this->formRow()->renderGroup($element, $elementString);
            break;
        default:
            echo $this->formRow($element);
            break;
    }
}

echo $this->form()->closeTag();
