<?php
/**
 * @copyright 2018 Internalsystemerror Limited
 */
declare(strict_types=1);

// Add buttons
$factory = new \Ise\Bread\Factory\FormAbstractFactory;
$factory->addButtonsToForm($changePasswordForm, 'Confirm');

// Set up email element
$email = $changePasswordForm->get('identity');
$email->setValue($this->identity()->getEmail());

// Set up cancel button
$cancel = $changePasswordForm->get('buttons')->get('cancel');
$cancel->setAttribute('href', $this->url('zfcuser/profile'));

// Prepare form
$changePasswordForm->remove('submit');
$changePasswordForm->setAttribute('action', $this->url());
$changePasswordForm->setAttribute('class', 'form-horizontal');
$changePasswordForm->setAttribute('autocomplete', 'off');
$changePasswordForm->prepare();

?>
    <h1 class="page-header">
        <?php echo $this->translate('Change Password'); ?>
    </h1>
<?php
if ($status === true) {
    echo $this->alert()->success('Password changed successfully.');
} elseif ($status === false) {
    echo $this->alert()->danger('Unable to update your password. Please try again.');
}
echo $this->form($changePasswordForm);
