<h1 class="page-header">
    Browsing User Accounts
</h1>
<table class="table table-striped table-bordered table-hover">
    <thead>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Display Name</th>
            <th>Email Address</th>
            <th>Last Modified</th>
            <th>Created</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <?php
        if ($this->isGranted($this->basePermission . '.browse')):
            foreach ($this->list as $user):
            ?>
            <tr<?php echo $user->isDisabled() ? ' class="danger"' : ($user->isBanned() ? ' class="warning"' : null) ?>>
                <td><?php echo $this->escapeHtml($user->getId()) ?></td>
                <td><?php echo $this->escapeHtml($user->getUsername()) ?></td>
                <td><?php echo $this->escapeHtml($user->getDisplayName()) ?></td>
                <td><?php echo $this->escapeHtml($user->getEmail()) ?></td>
                <td><?php echo $this->time($user->getLastModified()) ?></td>
                <td><?php echo $this->time($user->getCreated()) ?></td>
                <td>
                    <?php if ($user->isDisabled()): ?>
                        <?php if ($this->isGranted($this->basePermission . '.enable')): ?>
                    <a class="btn btn-success" role="button" title="Enable"
                       href="<?php echo $this->url('admin/users/enable', ['id' => $user->getId()]) ?>">
                        <span class="glyphicon glyphicon-off"></span>
                    </a>
                        <?php endif ?>
                    <?php else: ?>
                    <div class="btn-group" role="group" aria-label="Actions">
                        <?php if ($user->isBanned() && $this->isGranted($this->basePermission . '.unban')): ?>
                        <a class="btn btn-success" role="button" title="Unban"
                           href="<?php echo $this->url('admin/users/unban', ['id' => $user->getId()]) ?>">
                            <span class="glyphicon glyphicon-ban-circle"></span>
                        </a>
                        <?php elseif ($this->isGranted($this->basePermission . '.ban')): ?>
                        <a class="btn btn-warning" role="button" title="Ban"
                           href="<?php echo $this->url('admin/users/ban', ['id' => $user->getId()]) ?>">
                            <span class="glyphicon glyphicon-ban-circle"></span>
                        </a>
                        <?php endif ?>
                        <?php if ($this->isGranted($this->basePermission . '.disable')): ?>
                        <a class="btn btn-warning" role="button" title="Disable"
                           href="<?php echo $this->url('admin/users/disable', ['id' => $user->getId()]) ?>">
                            <span class="glyphicon glyphicon-off"></span>
                        </a>
                        <?php endif ?>
                        <?php if ($this->isGranted($this->basePermission . '.delete')): ?>
                        <a class="btn btn-danger" role="button" title="Delete"
                           href="<?php echo $this->url('admin/users/delete', ['id' => $user->getId()]) ?>">
                            <span class="glyphicon glyphicon-trash"></span>
                        </a>
                        <?php endif ?>
                    </div>
                    <?php endif ?>
                </td>
            </tr>
            <?php
            endforeach;
        endif;
        ?>
    </tbody>
</table>