<p>
    <strong>Are you sure</strong> you really want to
    <?php echo $actionTitle ?> the <?php echo $entityTitle ?>:
    <em><?php echo $entity ?></em>?
</p>
<?php
if ($entity->isPermanent()) {
    echo $this->alert()->danger(
        'Please note that you are about to disable a permanent '
        . $entityType . ', which can have serious adverse '
        . 'effects. Be sure you understand the implications of '
        . 'this action before proceeding.');
}
