<?php
$basePermission        = 'admin.rbac';
$rolesPermission       = $basePermission . '.roles';
$permissionsPermission = $basePermission . '.permissions';
?>
<h1 class="page-header">
    Roles & Permissions
</h1>
<?php if ($this->isGranted($rolesPermission . '.browse')): ?>
    <h3 class="page-header">
        Roles
    </h3>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Last Modified</th>
                <th>Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($roles as $role): ?>
                <tr<?php echo $role->isDisabled() ? ' class="danger"' : ($role->isPermanent() ? ' class="warning"' : null) ?>>
                    <td><?php echo $this->escapeHtml($role->getId()) ?></td>
                    <td><?php echo $this->escapeHtml($role->getName()) ?></td>
                    <td><?php echo $this->escapeHtml($role->getDescription()) ?></td>
                    <td><?php echo $this->time($role->getLastModified()) ?></td>
                    <td><?php echo $this->time($role->getCreated()) ?></td>
                    <td>
                        <?php if ($role->isDisabled() && $this->isGranted($rolesPermission . '.enable')): ?>
                            <a class="btn btn-success" role="button" title="Enable"
                               href="<?php echo $this->url('admin/roles/enable', array('id' => $role->getId())) ?>">
                                <span class="glyphicon glyphicon-off"></span>
                            </a>
                        <?php else: ?>
                            <div class="btn-group" role="group" aria-label="Actions">
                                <?php if ($this->isGranted($rolesPermission . '.disable')): ?>
                                    <a class="btn btn-warning" role="button" title="Disable"
                                       href="<?php echo $this->url('admin/roles/disable', array('id' => $role->getId())) ?>">
                                        <span class="glyphicon glyphicon-off"></span>
                                    </a>
                                <?php endif ?>
                                <?php if ($this->isGranted($rolesPermission . '.read')): ?>
                                    <a class="btn btn-primary" role="button" title="View"
                                       href="<?php echo $this->url('admin/roles/read', array('id' => $role->getId())) ?>">
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>
                                <?php endif ?>
                                <?php if ($this->isGranted($rolesPermission . '.edit')): ?>
                                    <a class="btn btn-info" role="button" title="Edit"
                                       href="<?php echo $this->url('admin/roles/edit', array('id' => $role->getId())) ?>">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                <?php endif ?>
                                <?php if (!$role->isPermanent() && $this->isGranted($rolesPermission . '.delete')): ?>
                                    <a class="btn btn-danger" role="button" title="Delete"
                                       href="<?php echo $this->url('admin/roles/delete', array('id' => $role->getId())) ?>">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                <?php endif ?>
                            </div>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
<?php endif ?>
<?php if ($this->isGranted($permissionsPermission . '.browse')): ?>
    <h3 class="page-header">
        Permissions
    </h3>
    <table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Last Modified</th>
                <th>Created</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($permissions as $permission): ?>
                <tr<?php echo $permission->isDisabled() ? ' class="danger"' : ($permission->isPermanent() ? ' class="warning"' : null) ?>>
                    <td><?php echo $this->escapeHtml($permission->getId()) ?></td>
                    <td><?php echo $this->escapeHtml($permission->getName()) ?></td>
                    <td><?php echo $this->escapeHtml($permission->getDescription()) ?></td>
                    <td><?php echo $this->time($permission->getLastModified()) ?></td>
                    <td><?php echo $this->time($permission->getCreated()) ?></td>
                    <td>
                        <?php if ($permission->isDisabled() && $this->isGranted($permissionsPermission . '.enable')): ?>
                            <a class="btn btn-success" role="button" title="Enable"
                               href="<?php echo $this->url('admin/permissions/enable', array('id' => $permission->getId())) ?>">
                                <span class="glyphicon glyphicon-off"></span>
                            </a>
                        <?php else: ?>
                            <div class="btn-group" role="group" aria-label="Actions">
                                <?php if ($this->isGranted($permissionsPermission . '.disable')): ?>
                                    <a class="btn btn-warning" role="button" title="Disable"
                                       href="<?php echo $this->url('admin/permissions/disable', array('id' => $permission->getId())) ?>">
                                        <span class="glyphicon glyphicon-off"></span>
                                    </a>
                                <?php endif ?>
                                <?php if ($this->isGranted($permissionsPermission . '.read')): ?>
                                    <a class="btn btn-primary" role="button" title="Disable"
                                       href="<?php echo $this->url('admin/permissions/read', array('id' => $permission->getId())) ?>">
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>
                                <?php endif ?>
                                <?php if ($this->isGranted($permissionsPermission . '.edit')): ?>
                                    <a class="btn btn-info" role="button" title="Disable"
                                       href="<?php echo $this->url('admin/permissions/edit', array('id' => $permission->getId())) ?>">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </a>
                                <?php endif ?>
                                <?php if (!$permission->isPermanent() && $this->isGranted($permissionsPermission . '.delete')): ?>
                                    <a class="btn btn-danger" role="button" title="Delete"
                                       href="<?php echo $this->url('admin/permissions/delete', array('id' => $permission->getId())) ?>">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </a>
                                <?php endif ?>
                            </div>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach ?>
        </tbody>
    </table>
    <?php endif ?>
