<?php echo $this->doctype() ?>
<html lang="en" class="no-js" id="html">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Internalsystemerror Limited') ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="loader-wrapper">
            <div id="loader"></div>
            <div id="loader-background"></div>
        </div>
        <?php
        echo $this->navigation('default_navigation')->navbar()->render(null, [
            'brand'     => [
                'label' => 'ISE',
                'route' => 'home',
                'icon'  => 'th-large'
            ],
            'inverse'   => true,
            'fixed'     => 'top',
            'rightMenu' => 'user_menu_navigation',
        ])

        ?>
        <div class="container-fluid">
            <div class="row">
                <main class="col-sm-12">
                    <?php echo $content ?>
                </main>
            </div>
            <?php echo $this->partial('partial/footer') ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
