<?php echo $this->doctype() ?>
<html lang="en" class="no-js" id="html">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Internalsystemerror Limited') ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div id="loader-wrapper">
            <div id="loader"></div>
            <div id="loader-background"></div>
        </div>
        <?php
        echo $this->navigation('admin_navigation')->navbar()->render(null, [
            'brand'     => [
                'label' => 'ISE',
                'route' => 'admin/index',
                'icon'  => 'th-large'
            ],
            'inverse'   => true,
            'fixed'     => 'top',
            'rightMenu' => 'admin_navigation_menu',
        ])

        ?>
        <div class="container-fluid">
            <div class="row">
                <!--
                <div class="col-sm-3 col-md-2 sidebar">
                    <ul class="nav nav-sidebar">
                        <li class="active">
                            <a href="#">Overview <span class="sr-only">(current)</span></a>
                        </li>
                        <li><a href="#">Reports</a></li>
                        <li><a href="#">Analytics</a></li>
                        <li><a href="#">Export</a></li>
                    </ul>
                </div>
                <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
                -->
                <div class="col-sm-12">
                    <?php echo $this->flashMessenger() ?>
                    <?php echo $content ?>
                </div>
            </div>
            <?php echo $this->partial('partial/footer') ?>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
