<?php echo $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Internalsystemerror Limited') ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div class="container-fluid">
            <div class="row">
                <main class="col-sm-12">
                    <?php echo $content ?>
                </main>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
