<?php echo $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Internalsystemerror Limited') ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headStyle() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <div class="container">
            <div class="form-signin">
                <?php echo $content ?>
                <?php echo $this->partial('partial/footer') ?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
